<?php

namespace AppBundle\Repository;

/**
 * promoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class promoRepository extends \Doctrine\ORM\EntityRepository
{
}
